---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 127.0.0.1
      ansible_connection: docker
vector:
  hosts:
    vector-01:
      ansible_host: 127.0.0.1
      ansible_connection: docker
