---
- name: Install Clickhouse
  hosts: clickhouse

  vars:
    clickhouse_version: "22.3.3.44"
    clickhouse_packages:
      - clickhouse-client
      - clickhouse-server
      - clickhouse-common-static

  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted

  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
            dest: "/tmp/{{ item }}-{{ clickhouse_version }}.rpm"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "/tmp/clickhouse-common-static-{{ clickhouse_version }}.rpm"

    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - /tmp/clickhouse-common-static-{{ clickhouse_version }}.rpm
          - /tmp/clickhouse-client-{{ clickhouse_version }}.rpm
          - /tmp/clickhouse-server-{{ clickhouse_version }}.rpm
      notify: Start clickhouse service

    - name: Flush handlers
      meta: flush_handlers

    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

- name: Install Vector
  hosts: vector

  vars:
    vector_version: "0.23.0"
    vector_install_dir: "/opt/vector"

  handlers:
    - name: Restart Vector
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted

  tasks:
    - name: Download Vector
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
        dest: "/tmp/vector-{{ vector_version }}.tar.gz"
        mode: '0644'

    - name: Create Vector directory
      ansible.builtin.file:
        path: "{{ vector_install_dir }}"
        state: directory
        mode: '0755'

    - name: Extract Vector
      ansible.builtin.unarchive:
        src: "/tmp/vector-{{ vector_version }}.tar.gz"
        dest: "{{ vector_install_dir }}"
        remote_src: yes
        extra_opts: ["--strip-components=2"]
        creates: "{{ vector_install_dir }}/bin/vector"

    - name: Install Vector binary
      ansible.builtin.copy:
        src: "{{ vector_install_dir }}/bin/vector"
        dest: /usr/bin/vector
        mode: '0755'
        remote_src: yes

    - name: Create Vector config directory
      ansible.builtin.file:
        path: /etc/vector
        state: directory
        mode: '0755'

    - name: Deploy Vector config
      ansible.builtin.template:
        src: templates/vector.yaml.j2
        dest: /etc/vector/vector.yaml
        mode: '0644'
      notify: Restart Vector

    - name: Create systemd service for Vector
      ansible.builtin.template:
        src: templates/vector.service.j2
        dest: /etc/systemd/system/vector.service
        mode: '0644'
      notify: Restart Vector

    - name: Start Vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: started
        enabled: yes
